name: Atiesh Release & Publish to GitHub Packages

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Master
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        
    ## Package
    - name: Package Core
      run: sbt 'project core; clean; package'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Package HttpUtils
      run: sbt 'project httputils; clean; package'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Package HttpSemantics
      run: sbt 'project http; clean; package'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Package FilesystemSemantics
      run: sbt 'project filesystem; clean; package'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Package KafkaSemantics
      run: sbt 'project kafka; clean; package'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Experiment
    - name: Package syslog
      run: sbt 'project syslog; clean; package'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Package aliyun
      run: sbt 'project aliyun; clean; package'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    ## Publish
    - name: Publish Core
      run: sbt 'project core; publish'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish HttpUtils
      run: sbt 'project httputils; publish'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish HttpSemantics
      run: sbt 'project http; publish'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish FilesystemSemantics
      run: sbt 'project filesystem; publish'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish KafkaSemantics
      run: sbt 'project kafka; publish'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Experiment
    - name: Publish syslog
      run: sbt 'project syslog; publish'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish aliyun
      run: sbt 'project aliyun; publish'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
